{
 "title": "Fraud Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "sum by (label) (fraud_prediction_count)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(label) (fraud_prediction_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Latency (p50 / p90 / p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(inference_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(inference_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(inference_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (predict_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fraud Score over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(fraud_score_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}